### ISSUE TITLE
Reaction and username with emoji

### ISSUE THREAD

**Issue by Mara-Li** [Vendicated/PowercordTwemojiEverywhere#1]
Hello ! I have a problem with the display of the reaction for people who have emoji in username : 
![image](https://user-images.githubusercontent.com/30244939/114436180-50b78880-9bc5-11eb-8b45-d5d40a575700.png)

**Comment by Vendicated** [comment]
thanks, I'll look into it!

**Comment by Vendicated** [comment]
I am not sure how to fix this, so I just made it so that twemoji isn't injected into reaction hover menus for now. 

The problem is that it replaces the literal emoji string with `<img>` tags which does not go along with the text wrap. I have no clue how to solve this :(

**Comment by Mara-Li** [comment]
It's a good temporary fix! Thanks :)

**Comment by kckarnige** [comment]
I think this might help
https://www.javascripting.com/view/emojify-js
